### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by vanillasoul93** [Quidrex/DSDeaths#3]
I was wondering how you were able to get the memory addresses for the deaths, if you could help me out in any way email me at davinw08@gmail.com

**Comment by gabman15** [comment]
Did u get a response. I'm incredibly curious as to how they found a static pointer to the death count in memory.

**Comment by Quidrex** [comment]
I used Cheat Engine which is a great tool for this kind of stuff. Basically I started a new file, found all memory locations that had the number 0 in it, died, filtered by 1 and so on until there was only one location left. When it's more than one location there is usually one that's more stable or updates earlier. That memory address was not the same after reloads, however a pointer to it was. For example the address for DS1 turned out to be [0xF78700]+0x5C while DS2 needed more indirections:[[[0x160B8D0]+0xD0]+0x490]+0x104.

**Comment by Quidrex** [comment]
Feel free to comment but I'll leave this closed as it is not an issue.
